# Generated by Django 4.1.2 on 2024-01-11 16:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='samb_apis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
                ('registration_date', models.CharField(max_length=14, verbose_name='Registration Date')),
                ('update_date', models.CharField(max_length=14, verbose_name='Update Date')),
                ('condition', models.CharField(max_length=1, verbose_name='Condition')),
            ],
            options={
                'verbose_name': 'samb_apis',
                'verbose_name_plural': 'samb_apis',
                'db_table': 'samb_apis',
            },
        ),
    ]
