# Generated by Django 4.1.2 on 2024-01-11 16:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_samb_api_financial_asset'),
    ]

    operations = [
        migrations.CreateModel(
            name='samb_cronjobs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.CharField(max_length=14, verbose_name='Start Date')),
                ('end_date', models.CharField(max_length=255, verbose_name='End Date')),
                ('condition', models.CharField(max_length=1, verbose_name='Condition')),
                ('id_samb_api', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.samb_apis')),
                ('id_samb_financial_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.samb_financial_asset')),
            ],
            options={
                'verbose_name': 'samb_cronjobs',
                'verbose_name_plural': 'samb_cronjobs',
                'db_table': 'samb_cronjobs',
            },
        ),
    ]
