# Generated by Django 4.1.2 on 2024-01-11 16:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_samb_notification_conditions'),
    ]

    operations = [
        migrations.CreateModel(
            name='samb_send_message_api_whatsapp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_message_api', models.CharField(max_length=100, verbose_name='cod_message_api')),
                ('recipient_phone_number', models.CharField(max_length=20, verbose_name='Recipient_Phone_Number')),
                ('start_date', models.CharField(max_length=14, verbose_name='Start Date')),
                ('udpate_date', models.CharField(max_length=14, verbose_name='Update Date')),
                ('condition', models.CharField(max_length=1, verbose_name='Condition')),
                ('id_samb_notification_conditions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.samb_notification_conditions')),
            ],
            options={
                'verbose_name': 'samb_send_message_api_whatsapp',
                'verbose_name_plural': 'samb_send_message_api_whatsapp',
                'db_table': 'samb_send_message_api_whatsapp',
            },
        ),
    ]
