# Generated by Django 4.1.2 on 2024-01-11 16:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_samb_send_message_api_whatsapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='samb_movements',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_entity', models.CharField(default='111111111', max_length=100, verbose_name='Id entity')),
                ('open', models.CharField(max_length=10, verbose_name='Open')),
                ('close', models.CharField(max_length=10, verbose_name='Close')),
                ('min', models.CharField(max_length=10, verbose_name='Min')),
                ('max', models.CharField(max_length=10, verbose_name='Max')),
                ('registration_date', models.CharField(max_length=14, verbose_name='Registration Date')),
                ('update_date', models.CharField(max_length=14, verbose_name='Update Date')),
                ('condition', models.CharField(max_length=1, verbose_name='Condition')),
                ('id_cronjobs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.samb_cronjobs')),
                ('id_financial_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.samb_financial_asset')),
            ],
            options={
                'verbose_name': 'samb_movements',
                'verbose_name_plural': 'samb_movements',
                'db_table': 'samb_movements',
            },
        ),
    ]
