# Generated by Django 4.1.2 on 2024-02-01 22:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0012_samb_notifications_exceptions_apis_independient'),
    ]

    operations = [
        migrations.CreateModel(
            name='samb_shedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('start_date', models.CharField(max_length=14, verbose_name='Start Date')),
                ('end_date', models.CharField(max_length=255, verbose_name='End Date')),
                ('registration_date', models.CharField(max_length=14, verbose_name='Registration Date')),
                ('update_date', models.CharField(max_length=14, verbose_name='Update Date')),
                ('condition', models.CharField(max_length=1, verbose_name='Condition')),
            ],
            options={
                'verbose_name': 'samb_shedule',
                'verbose_name_plural': 'samb_shedule',
                'db_table': 'samb_shedule',
            },
        ),
    ]
