# Generated by Django 4.1.2 on 2024-02-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0013_samb_shedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samb_cronjobs',
            name='end_date',
            field=models.CharField(max_length=14, verbose_name='End Date'),
        ),
    ]
