# Generated by Django 4.1.2 on 2024-02-07 16:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0014_alter_samb_cronjobs_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='samb_entrys',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=14, verbose_name='Type')),
                ('type_account', models.CharField(default='PRACTICE', max_length=14, verbose_name='Type Account')),
                ('number_candle', models.CharField(default='5', max_length=1, verbose_name='Number Candle')),
                ('condition_entry', models.CharField(default='CLOSE', max_length=10, verbose_name='Contition Entry')),
                ('amount', models.CharField(max_length=14, verbose_name='Amount')),
                ('operations_results', models.CharField(default='REALIZADA', max_length=14, verbose_name='Operations Results')),
                ('registration_date', models.CharField(max_length=14, verbose_name='Registration Date')),
                ('update_date', models.CharField(max_length=14, verbose_name='Update Date')),
                ('condition', models.CharField(max_length=1, verbose_name='Condition')),
                ('indicators', models.CharField(default='0', max_length=1, verbose_name='Indicators')),
                ('id_samb_cronjobs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.samb_cronjobs')),
            ],
            options={
                'verbose_name': 'samb_entrys',
                'verbose_name_plural': 'samb_entrys',
                'db_table': 'samb_entrys',
            },
        ),
    ]
