# Generated by Django 4.1.2 on 2024-02-10 20:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0015_samb_entrys'),
    ]

    operations = [
        migrations.CreateModel(
            name='samb_framework',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(default='Test', max_length=14, verbose_name='Description')),
                ('registration_date', models.CharField(max_length=14, verbose_name='Registration Date')),
                ('condition', models.CharField(max_length=1, verbose_name='Condition')),
            ],
            options={
                'verbose_name': 'samb_framework',
                'verbose_name_plural': 'samb_framework',
                'db_table': 'samb_framework',
            },
        ),
    ]
