# Generated by Django 4.1.2 on 2024-02-14 20:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0016_samb_framework'),
    ]

    operations = [
        migrations.CreateModel(
            name='samb_config',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(default='api-key', max_length=10, verbose_name='key')),
                ('value', models.CharField(max_length=100, verbose_name='Value')),
                ('registration_date', models.CharField(max_length=14, verbose_name='Registration Date')),
                ('condition', models.CharField(max_length=1, verbose_name='Condition')),
            ],
            options={
                'verbose_name': 'samb_config',
                'verbose_name_plural': 'samb_config',
                'db_table': 'samb_config',
            },
        ),
    ]
