# Generated by Django 4.1.2 on 2024-02-15 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0017_samb_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samb_entrys',
            name='indicators',
        ),
        migrations.AddField(
            model_name='samb_entrys',
            name='id_entry_platform',
            field=models.CharField(default='11111111', max_length=20, verbose_name='Entry Platform'),
        ),
        migrations.AddField(
            model_name='samb_entrys',
            name='result_platform',
            field=models.CharField(default='NONE', max_length=14, verbose_name='Results Platform'),
        ),
    ]
