# Generated by Django 4.1.2 on 2024-02-15 21:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0019_remove_samb_entrys_operations_results'),
    ]

    operations = [
        migrations.CreateModel(
            name='samb_indicators',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
                ('registration_date', models.CharField(max_length=14, verbose_name='Registration Date')),
                ('condition', models.CharField(max_length=1, verbose_name='Condition')),
            ],
            options={
                'verbose_name': 'samb_indicators',
                'verbose_name_plural': 'samb_indicators',
                'db_table': 'samb_indicators',
            },
        ),
        migrations.CreateModel(
            name='samb_indicators_entrys',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registration_date', models.CharField(max_length=14, verbose_name='Registration Date')),
                ('condition', models.CharField(max_length=1, verbose_name='Condition')),
                ('id_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.samb_entrys')),
                ('id_indicators', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.samb_indicators')),
            ],
            options={
                'verbose_name': 'samb_indicators_entrys',
                'verbose_name_plural': 'samb_indicators_entrys',
                'db_table': 'samb_indicators_entrys',
            },
        ),
    ]
