# Generated by Django 4.1.2 on 2024-02-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0021_samb_indicators_entrys_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samb_indicators_entrys',
            name='value',
            field=models.CharField(default='0', max_length=20, verbose_name='Value'),
        ),
    ]
