# Generated by Django 4.1.2 on 2024-02-16 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0022_alter_samb_indicators_entrys_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samb_movements',
            name='close',
        ),
        migrations.RemoveField(
            model_name='samb_movements',
            name='id_cronjobs',
        ),
        migrations.RemoveField(
            model_name='samb_movements',
            name='id_entity',
        ),
        migrations.RemoveField(
            model_name='samb_movements',
            name='id_financial_asset',
        ),
        migrations.RemoveField(
            model_name='samb_movements',
            name='max',
        ),
        migrations.RemoveField(
            model_name='samb_movements',
            name='min',
        ),
        migrations.RemoveField(
            model_name='samb_movements',
            name='open',
        ),
        migrations.AddField(
            model_name='samb_movements',
            name='at_candle',
            field=models.CharField(default='0', max_length=20, verbose_name='Open'),
        ),
        migrations.AddField(
            model_name='samb_movements',
            name='close_candle',
            field=models.CharField(default='0', max_length=20, verbose_name='Close'),
        ),
        migrations.AddField(
            model_name='samb_movements',
            name='from_candle',
            field=models.CharField(default='0', max_length=20, verbose_name='Open'),
        ),
        migrations.AddField(
            model_name='samb_movements',
            name='id_entity_candle',
            field=models.CharField(default='0', max_length=20, verbose_name='Id entity'),
        ),
        migrations.AddField(
            model_name='samb_movements',
            name='id_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.samb_entrys'),
        ),
        migrations.AddField(
            model_name='samb_movements',
            name='max_candle',
            field=models.CharField(default='0', max_length=20, verbose_name='Max'),
        ),
        migrations.AddField(
            model_name='samb_movements',
            name='min_candle',
            field=models.CharField(default='0', max_length=20, verbose_name='Min'),
        ),
        migrations.AddField(
            model_name='samb_movements',
            name='open_candle',
            field=models.CharField(default='0', max_length=20, verbose_name='Open'),
        ),
        migrations.AddField(
            model_name='samb_movements',
            name='to_candle',
            field=models.CharField(default='0', max_length=20, verbose_name='Open'),
        ),
        migrations.AddField(
            model_name='samb_movements',
            name='volume_candle',
            field=models.CharField(default='0', max_length=20, verbose_name='Max'),
        ),
    ]
