# Generated by Django 4.1.2 on 2024-02-19 20:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0023_remove_samb_movements_close_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='samb_send_message_api_telegram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=14, verbose_name='Type')),
                ('message', models.CharField(max_length=100, verbose_name='Message')),
                ('chat', models.CharField(max_length=20, verbose_name='Chat')),
                ('response_method', models.CharField(max_length=100, verbose_name='Response Method')),
                ('registration_date', models.CharField(max_length=14, verbose_name='Registration Date')),
                ('update_date', models.CharField(max_length=14, verbose_name='Update Date')),
                ('condition', models.CharField(max_length=1, verbose_name='Condition')),
                ('id_cronjobs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.samb_cronjobs')),
            ],
            options={
                'verbose_name': 'samb_send_message_api_telegram',
                'verbose_name_plural': 'samb_send_message_api_telegram',
                'db_table': 'samb_send_message_api_telegram',
            },
        ),
    ]
