# Generated by Django 4.1.2 on 2024-02-23 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0024_samb_send_message_api_telegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='samb_cronjobs',
            name='execution_time',
            field=models.CharField(default='0', max_length=110, verbose_name='execution_time'),
        ),
    ]
