name: Despliegue automático en push a analized-secrets

on:
  push:
    branches:
      - analized-secrets

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Desplegar
        run: |
          export EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}

      - name: Verificar
        run: |

            # Puedes acceder a las variables de entorno configuradas anteriormente
            echo "La clave de correo es: $EMAIL_PASSWORD"
            # Agrega aquí los comandos para desplegar tu aplicación con la clave de correo