name: Despliegue automático en push a main

on:
  push:
    branches:
      - analized-secrets

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Configurar secretos
        run: |
          echo "EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}" >> $GITHUB_ENV
          # Puedes agregar más variables de entorno según sea necesario

      - name: Desplegar
        run: |
          # Puedes acceder a las variables de entorno configuradas anteriormente
          echo "La clave de correo es: $EMAIL_PASSWORD"
          echo "La longitud de la clave de correo es: ${#EMAIL_PASSWORD}"
          # Agrega aquí los comandos para desplegar tu aplicación con la clave de correo
