name: Secrets

on:
  push:
    branches:
      - analized-secrets

jobs:      
  run-configuration:
    name: ⚙ Composer
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: github.event.inputs.command  == 'Composer-Install' || github.event.inputs.command  == 'Migrations'
    steps:
    - name: ⚙ Install Dependencies
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SSH_SERVER }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        command_timeout: 30m
        script: | 
        
          source /home/guarvzpf/virtualenv/dev/3.8/bin/activate && cd /home/guarvzpf/dev
          echo "hola"
